[command]
name = "byeiso"
keywords = [ ]
enabled = false
content = """
## ISOs are now deprecated!

Starting with 23.09, there will no longer be any ISO releases, and the only remaining installation method is the playbook. We've made this decision because its a lot of work to maintain **4 ISOs + Playbook + Revision tool + Revision website**, most of which is being done by h3r0 alone. ||Plus, ISO distribution is against the Microsoft TOS.||

Playbooks have matured a lot since their release, and both we and the AME devs have learned a bunch about how to do playbooks right. We'll update our website documentation soon.

## If you installed ReviOS via ISO

You can transfer without problems to a playbook installation:
1. enable windows update through the Revision tool
2. install all available updates
3. disable updates through the Revision tool
4. run the newest avaiable Playbook in the AME Wizard
"""

[embed]
enabled = true
