[command]
name = "ddu"
keywords = ["graphic", "uninstall", "driver"]
enabled = true
content = """
If you are having issues with your graphic drivers, we recommend uninstalling and reinstalling the drivers. To do so, please go through following steps:

1. Use Display Driver Uninstaller to remove the current installed drivers. [This guide](https://www.wagnardsoft.com/content/DDU-Guide-Tutorial) explains the whole procedure (even if slightly outdated).
2. Once drivers have been uninstalled, proceed with installing the drivers you downloaded in Step 1 of the guide above.
3. Once drivers have been installed, reboot your PC. Drivers should be ready now.

Note: If you use a Nvidia GTX 1600, RTX 3000 or AMD RX 5000/6000/7000 series user, it is highly recommended to disable Multiplane Overlay (MPO) after installation of drivers. 
You can use the NVIDIA method [here](https://nvidia.custhelp.com/app/answers/detail/a_id/5157/~/after-updating-to-nvidia-game-ready-driver-461.09-or-newer%2C-some-desktop-apps) which also works for AMD cards or use [this tool](https://github.com/RedDot-3ND7355/MPO-GPU-FIX).
"""

[embed]
enabled = true
