# This is the main section for defining a command configuration.
[command]
name = "defender-icon"
keywords = [ "defender", "tray" ]
enabled = true
content = """
To Restore the Windows Defender Icon in the System Tray, execute these commands in a Command Prompt:
```
reg add "HKLM\\SOFTWARE\\Policies\\Microsoft\\Windows Defender Security Center\\Systray" /v HideSystray /t REG_DWORD /d 0 /f
reg add "HKEY_LOCAL_MACHINE\\SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\Explorer\\StartupApproved\\Run" /v SecurityHealth /t REG_BINARY /d 060000000000000000000000 /f
reg add "HKEY_LOCAL_MACHINE\\SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\Run" /v SecurityHealth /t REG_EXPAND_SZ /d "%windir%\\system32\\SecurityHealthSystray.exe" /f
```
"""

[embed]
enabled = true
