[command]
name = "devuploads"
keywords = ["money", "donate", "support", "contribute"]
enabled = true
content = """
`The download site is riddled with ads!`

Yes, we are sorry about that. We run this project in our free time just for fun, and no one gets paid. The ads help cover things like server costs and other expenses.

If you'd like to avoid the ads, we also provide alternative download links on our GitHub: https://github.com/meetrevision/playbook/releases/latest

If you want to support the project and help reduce the ads, feel free to donate here: https://www.buymeacoffee.com/meetrevision
"""

[embed]
enabled = true
