[command]
name = "fafo"
keywords = ["fuck around and find out"]
enabled = true
content = """
https://tenor.com/view/find-out-fuck-around-fuck-around-and-find-out-gif-27076170
"""

[embed]
enabled = false
