[command]
name = "fan-curve"
keywords = ["fans", "loud", "quiet", "curve"]
enabled = true
content = """
**Fan curve example by KGTC**
"""

[embed]
enabled = true
image = "https://i.imgur.com/mkzM6VQ.png"
