[command]
name = "features"
keywords = ["details", "info"]
enabled = true
content = """
To get a full list of ReviOS's features, please visit the following link:

https://revi.cc/docs/features
"""

[embed]
enabled = true
