[command]
name = "features"
keywords = ["details", "info"]
enabled = true
content = """
To get a full list of ReviOS's features, please visit the following link:

https://www.revi.cc/docs/faq/before/features
"""

[embed]
enabled = true
