[command]
name = "finals"
keywords = [ ]
enabled = true
content = """
**To Fix the EAC Error in The Finals do the following:**

1. Open a new Terminal window
2. Paste in the following command: `reg add "HKLM\\SYSTEM\\CurrentControlSet\\Control\\CI\\Config" /v "VulnerableDriverBlocklistEnable" /t REG_DWORD /d "1" /f`
3. Reboot your PC
"""

[embed]
enabled = true
