[command]
name = "firefox"
keywords = ["browser", "web", "internet"]
enabled = true
content = """
To get rid off **all** of your Firefox bookmarks, opne a new terminal as administrator and paste the following into it:
`reg delete "HKCU\\Software\\Policies\\Mozilla\\Firefox\\Bookmarks" /f`

If you want to get rid of all pre-configured Firefox settings paste the following into it
`reg delete "HKCU\\Software\\Policies\\Mozilla\\Firefox" /f`
"""

[embed]
enabled = true
