[command]
name = "games"
keywords = [ ]
enabled = true
content = """
## Game Launchers

In case some games launcher are not working on your ReviOS system, please try out alternatives

<https://www.revi.cc/docs/faq/after/game-launchers>
"""

[embed]
enabled = true
