[command]
name = "gamelaunchers"
keywords = [ ]
enabled = true
content = """
## Game Launchers

If for some reason, a game launcher is not working on your ReviOS system, please check out these alternatives:

<https://www.revi.cc/docs/faq/after/game-launchers>
"""

[embed]
enabled = true
