[intelfix]
embed = true
enabled = false
content = """
The fix is mainly for users who you are having issues with scheduler on Intel 12+ gen CPUs.

**How does it work?**

• Prevents parking of multi-threads (don't confuse it with cores parking)
• Prefers to use P||erformance||-cores for foreground applications and heavy load situations
• ~~Prefers to use E||fficient||-cores for background applications~~ (not necessary)


Recommended to run Terminal/Powershell as administrator. The settings are only applied for Ultra Powerplan.

```powershell
powercfg -s 3ff9831b-6f80-4830-8178-736cd4229e7b
powercfg -setacvalueindex scheme_current sub_processor HETEROPOLICY 0
powercfg -setacvalueindex scheme_current sub_processor SCHEDPOLICY 2
```
"""
