[command]
name = "latencymon"
keywords = ["gaming", "tweaks", "performance"]
enabled = true
content = """
Seeing a bad LatencyMon result? Don't worry, you shouldn't use it anyways. 

From their **own** page: *"LatencyMon checks if a system running Windows is suitable for processing __real-time audio__ and other tasks."*

LatencyMon measures latency in microseconds. To give some context:
```
1 second = 1,000,000 microseconds
1 millisecond = 1,000 microseconds
```

For gaming, even a few milliseconds of latency can feel significant, but the driver latency measured (such as 3000 microseconds, or 3 milliseconds) only accounts for a small portion of overall input delay. Other factors, like frame rendering time and network lag, usually contribute much more to the total gameplay latency.

Please also see here:
[`Stop Using LatencyMon to Improve Gaming Performance`](https://hone.gg/blog/stop-using-latencymon-to-improve-gaming-performance)
[`LatencyMon and how people use it`](https://linustechtips.com/topic/1588059-latencymon-and-how-people-use-it/#comment-16567126)
"""

[embed]
enabled = true
image = "https://hone.gg/images/image_2024-10-30_214025249_1image_2024-10-30_214025249.webp"
