# This is the main section for defining a command configuration.
[command]

# The name of the command. This is how the command will be referenced or called.
name = "ltsc"

# Keywords associated with the command. This is an empty array and can be populated with relevant keywords.
keywords = [ iot ]

# Boolean flag to indicate whether the command is enabled or not.
enabled = true

# The actual content or message that the command will output. This can be a multiline string.
content = """
Microsoft releases Windows 10 and 11 through two servicing channels.

1. GAC (General Availability Channel)
  - It is intended for both general and enterprise customers.
  - Edition examples include options such as Home, Pro, and Enterprise.
  - Maximum support on the same build is usually 2 years for consumers and 3 years for the enterprise. After that, you need to install feature updates.
  - This is the main servicing channel and other software and games usually follow this channel's life cycle to provide support.
2. LTSC (Long-Term Servicing Channel)
  - It is designed for devices where functionality and features must remain constant over time, such as medical systems, industrial controllers, and air traffic control devices.
  - Examples of editions include: Enterprise LTSC and IoT Enterprise LTSC.
  - Maximum support on the same build is usually 5 years for LTSC and 10 years for the IoT LTSC.
  - This is not the main servicing channel and other software and games usually don't follow this channel's life cycle. For example, browsers and games might not provide support for 10 years on same build.
  - It lacks most of the Store (UWP) apps.

## Reasons to use LTSC
- You don't like annual Windows feature upgrades.
- You don't like preinstalled Store (UWP) apps as well.
- You want longer update support for Windows 10.

## Reasons to avoid using LTSC:
- As stated above, many games and software might not support LTSC once that same build has reached the end of life in GAC.
- Games might not work out of the box and you will manually need to install store and Xbox apps.
- New hardware might not be fully supported by a 2-3 year-old LTSC build (A new version of LTSC is released every 3 years).
- You might miss new features added in GAC that aren't available in LTSC.
"""

# This section defines the configuration for embedding content.
[embed]

# Boolean flag to indicate whether embedding is enabled or not.
enabled = true

# (Optional) The color to be used in the embed, specified as a hex color code.
# This field is not mandatory as it will default to the Revision's Red Color if not provided.
# Ensure the color code is valid (e.g., "#FFFFFF" for white).
# color = "#FFFFF"

# (Optional) The URL of an image to be displayed in the embed.
# This should be a valid link to an image. If not needed, this line can be omitted.
image = "https://media.discordapp.net/attachments/626772503473291295/1332803320909271100/lOkMvQO.png?ex=67969551&is=679543d1&hm=66b3064b049133fe9e6867721f1e7f37f274befe55c582ba4bd019b2cc517481&=&format=webp&quality=lossless"
