[meme-uncle]
embed = false
image = "https://tenor.com/view/mauzymice\\-mauzy\\-mauzy\\-mice\\-silly\\-silly\\-cat\\-gif\\-16562063169824368899"
enabled = false
content = """
## [this is you](https://tenor.com/view/mauzymice\\-mauzy\\-mauzy\\-mice\\-silly\\-silly\\-cat\\-gif\\-16562063169824368899)
"""
