[command]
name = "minecraft"
keywords = [ ]
enabled = true
content = """
The new Minecraft launcher requires Windows Updates enabled and installs UWP bloat (useless Xbox apps). The classic Minecraft Launcher still works perfectly and should be used instead.
 
<https://launcher.mojang.com/download/MinecraftInstaller.msi>
"""

[embed]
enabled = true
