[mpo]
embed = true
enabled = true
content = """
Multi-Plane Overlay (MPO)

Is part of the Windows Display Driver Module (WDDM) 1.3 and it is designed to reduce CPU and GPU load when executing multiple frame buffers. Interestingly, the feature has had problems almost since the day it was launched and Microsoft has previously sent out fixes to address those issues.

Nvidia has said users can disable MPO through the registry, but no permanent fix is available from any of the companies. Symptoms of this problem include black screen, stuttering, flickering, and other general display problems.

If you are using an GTX 16xx, RTX 3xxx or an AMD RX 5xxx or newer it is highly recommended to disable MPO, one way to do so is by using [Nvidia's method](https://nvidia.custhelp.com/app/answers/detail/a_id/5157) or by using the latest Revision-Tool.
"""
