[command]
name = "mw2fix"
keywords = [ ]
enabled = true
content = """
**MW2 quick fix for older winvers**

`reg add "HKLM\\SOFTWARE\\Microsoft\\Windows NT\\CurrentVersion" /v "UBR" /t REG_DWORD /d "789" /f`
"""

[embed]
enabled = true
