[command]
name = "nousb"
keywords = ["install", "windows"]
enabled = true
content = """
**If you don't have a flash drive:**

https://github.com/iidanL/InstallWindowsWithoutUSB
"""

[embed]
enabled = true
