[command]
name = "office"
keywords = [ ]
enabled = true
content = """
**Office Tool Plus**
A powerful and useful tool for Office deployments.

<https://otp.landian.vip/en-us/download.html>
"""

[embed]
enabled = true
