name = "pb/nightly"
aliases = [ ]
embed = true
enabled = true
content = """
## ReviOS Nightly builds

If you want the latest, **bleeding-edge**, playbook version, go to the following repository: [ReviOS_playbook_nightly_insider](https://github.com/Pyenb/ReviOS_playbook_nightly_insider) by <@498138129991991296>.

This is an **unofficial** fork of ReviOS, including the following features:
- Nightly builds (**Everything** that gets committed to the main repository, is also included in this playbook)
- Windows Insider support (This playbook has support for the latest windows insider builds)

### **WARNING**:

⚠️〡The nightly builds are not tested and may not work. **Use at your own risk!**
⚠️〡**NO Support will be provided for them!**

Or, go directly to [releases](https://github.com/Pyenb/ReviOS_playbook_nightly_insider/releases/latest).
"""
