name = "pb"
aliases = [ ]
embed = true
enabled = true
content = """
## Playbooks are the future
Playbooks convert a Windows Stock install to ReviOS. You need to install your desired stock version first, then apply the Playbook on top of it.

**Installation via ISO is no longer available.** We've made this decision because its a lot of work to maintain 4 ISOs + Playbook + Revision tool + Revision website, most of which is being done by h3r0 alone. Plus, ISO distribution is against the Microsoft TOS.

## Installation Instructions
The instructions to installing ReviOS with the Playbook are under https://revi.cc/docs/playbook/general.

If you've previously installed ReviOS from an ISO, you can [update your install](https://revi.cc/docs/playbook/install/#update) with the Playbook without problems.

## Getting Stock ISOs
A direct link to stock Windows ISOs can be found [in our docs](https://revi.cc/docs/playbook/installwindows/#downloading-the-windows-iso)
"""
