[command]
name = "playbook/update"
keywords = ["windows", "revios", "revision", "latest"]
enabled = true
content = """
## Updating your install with Playbooks

1. Enable the Windows Update panel in the Revision tool
2. Install all updates that you wish to have
3. Once all updates are finalized, re-run the [latest available Playbook](https://github.com/meetrevision/playbook/releases/latest)

Read in the docs: https://revi.cc/docs/playbook/install#update
"""

[embed]
enabled = true
