[command]
name = "playbook/uninstall"
keywords = ["windows", "revios", "revision", "remove"]
enabled = true
content = """
# ReviOS cannot easily be uninstalled
It does permanent changes to the system and registry which **__cannot be reverted.__** 
To completely remove ReviOS, you **have to reinstall Windows**!

## Re-enabling disabled system components
⚠️〡This **will not** remove ReviOS fully!
⚠️〡This **will not** bring back removed APPX packages or revert registry modifications!

Open a new PowerShell window as administrator and paste the following command:
```powershell
Get-WindowsPackage -online -PackageName *ReviOS* | Remove-WindowsPackage -Online
```
If the command completes without any errors, restart your PC. The system components should now be re-enabled.
"""

[embed]
enabled = true
