[command]
name = "playbook/uninstall"
keywords = ["windows", "revios", "revision", "remove"]
enabled = true
content = """
# ReviOS cannot easily be uninstalled
It does permanent changes to the system and registry which **__cannot be reverted.__** 
To completely remove ReviOS, you **have to reinstall Windows**!

Before doing so, run these two commands one by one in a Powershell window:
```powershell
& "${env:ProgramFiles(x86)}/Revision Tool/revitool.exe" winpackage --uninstall system-components-removal
& "${env:ProgramFiles(x86)}/Revision Tool/revitool.exe" winpackage --uninstall defender-removal
```
"""

[embed]
enabled = true
