[command]
name = "playbook/versions"
keywords = ["windows", "revios", "revision", "compatible"]
enabled = true
content = """
https://github.com/meetrevision/playbook#-system-requirements
"""

[embed]
enabled = false
