[command]
name = "pleasegoogle"
keywords = ["browser", "search"]
enabled = true
content = """
Please just google it. We are not a search engine. We do this for fun, not to be your personal assistant.
"""

[embed]
enabled = true
image = "https://i.imgur.com/j1FgVb7.jpg"
