[command]
name = "postinstall"
keywords = ["windows", "revios", "revision", "faq"]
enabled = true
content = """
**ReviOS post-install guide**

https://www.revi.cc/docs/post-install
"""

[embed]
enabled = true
