[command]
name = "proc"
keywords = ["process count", "tweaks", "gaming"]
enabled = true
content = """
https://web.archive.org/web/20240207202953/https://zusier.xyz/blog/posts/process-count-doesnt-matter/
"""

[embed]
enabled = false
