[command]
name = "revisiontool"
keywords = ["windows", "revios", "revision", "custom", "tweaks"]
enabled = true
content = """
Download the latest Revision Tool:

https://github.com/MeetRevision/revision-tool/releases/latest
"""

[embed]
enabled = true
