[command]
name = "roblox"
keywords = [ ]
enabled = true
content = """
If Roblox wont open, have a look at this help section from AtlasOS: https://docs.atlasos.net/faq-and-troubleshooting/common-questions/roblox-not-opening
"""

[embed]
enabled = true
