name = "rufus"
aliases = [ ]
embed = true
enabled = true
content = """
On older versions of Rufus **select Standard at Image options**. 
On newer versions when **a window pops up** with the options to remove Secure Boot and TPM or RAM and disk or Microsoft account requirements or disable data collection, **select neither**. **ReviOS skips all of these already.**
"""
