[command]
name = "sec"
keywords = [ ]
enabled = false
content = """
If you have an **error** in the script that runs right after your Windows boots up the first time, **ignore it**.

Also, you only need to press Enter or Esc if you selected a character in the terminal window. See the [related FAQ section](https://www.revi.cc/docs/faq/during/cmd)
"""

[embed]
enabled = true
