name = "shrinkme"
aliases = [ ]
embed = true
image = "https://media.discordapp.net/attachments/672162269202874370/1116619500826140683/beb411f642348768.PNG?width=1414&height=1038"
enabled = false
content = """
**__Having trouble opening the shrinke.me links?__**

If you cannot open the ShrinkMe links from the download page due to any reason, you have the following options

- Become a Server Booster or [donate to Revision](<https://www.buymeacoffee.com/meetrevision>) to receive access to direct download links in the server
- Use a VPN to circumvent regional blocking of ShrinkMe
- Use the discord search function to find links in the server, since they get posted every once in a while

Staff **will not** hand out direct links if you ask about the page being broken.
"""
