[command]
name = "testing"
keywords = [ ]
enabled = true

content = """
Username: ${username}
mention: ${mention}

Guild Name: ${guildName}
Guild ID: ${guildId}
Channel Name: ${channelName}
"""

[embed]
enabled = false
