[command]
name = "testing"
keywords = [ ]
enabled = true

content = """
Hello ${user.name}, you are running this command on ${guild.name} in the ${channel.name} channel <:kek_facepalm:1163475465844031554>
"""

[embed]
enabled = false
