[tpm]
embed = true
enabled = true
content = """
## Should you enable TPM or Secure Boot?

General Answer: **no**. They are usually of no benefit to you and will only limit you. More detail [here](https://discord.com/channels/619835916139364383/626772503473291295/1172128280611139637).

When installing Stock Windows 11, the [Revision Ventoy Config](<https://revi.cc/docs/playbook/installstock/#apply-revios-config>) disables the TPM+SB requirements, so you can install W11 with them disabled.

### Exception
Valorant and FaceIT require both TPM and SB to be **enabled** when running on Windows 11. If you plan to play these games, it is recommended to **stick with Windows 10** instead. If you really want W11 though, you will have to enable TPM and SB.
"""
