[command]
name = "tpm"
keywords = ["secure boot", "security", "trusted platform module"]
enabled = true
content = """
## Should you enable TPM or Secure Boot?

General Answer: **no**. They are usually of no benefit to you and will only limit you. More detail [here](https://discord.com/channels/619835916139364383/626772503473291295/1172128280611139637).

If you use ISO Injection to install ReviOS, the requirement for TPM and Secure Boot will be bypassed automatically.

### Exception
Valorant, League of Legends and FaceIT require both TPM and SB to be **enabled** when running on Windows 11. If you plan to play these games, it is recommended to **stick with Windows 10** instead. If you really want W11 though, you will have to enable TPM and SB.
"""

[embed]
enabled = true
