[command]
name = "tutorial"
keywords = ["how to", "guide", "help"]
enabled = true
content = """
**Help to install and update ReviOS using AME Wizard available here:**
https://revi.cc/docs/playbook/install#-applying-playbook
 


**Community Videos:**
🟨 English Video by <@275019252036272128>
<https://youtu.be/d2CLBZZZgJA>

🟥 Chinese (Traditional) Video by <@809771061742010408>
<https://youtu.be/pQj2GIyD89Y>
"""

[embed]
enabled = true
