[command]
name = "tweaks"
keywords = ["ctb"]
enabled = true
content = """
# Tweaks

❗ We're NOT responsible for any direct or indirect consequences/damage resulting from their use.

###  🌟 General Advices
- Undervolt your CPU and GPU
- Enable XMP/EXPO in BIOS
- Minimize installation of apps, if possible search for lighter solutions (Tool: [BullCrapUninstaller](https://www.bcuninstaller.com/))
- Minimize startup items on your system (Tool: [Autoruns](https://learn.microsoft.com/en-us/sysinternals/downloads/autoruns))

### 🔸 Network Optimization Guide

https://www.intel.com/content/www/us/en/support/articles/000005811/ethernet-products.html

### ♦️ System Optimization Guides
https://www.calypto.us/
https://github.com/valleyofdoom/PC-Tuning
https://github.com/djdallmann/GamingPCSetup/
https://github.com/BoringBoredom/PC-Optimization-Hub
"""

[embed]
enabled = true
