[command]
name = "vcredist"
keywords = [ ]
enabled = true
content = """
**AIO Repack for latest Microsoft Visual C++ Redistributable Runtimes**

https://www.revi.cc/docs/post-install#visual-c-runtime
"""

[embed]
enabled = true
