[command]
name = "ventoy-config"
keywords = ["usb", "boot", "configuration"]
enabled = true
content = """
**Revision Configuration for Ventoy**
https://github.com/meetrevision/ventoy-config
"""

[embed]
enabled = true
