[command]
name = "wallpaper/anime"
keywords = [ ]
enabled = false
content = """
https://cdn.discordapp.com/attachments/629690919263666191/1198016282956664914/new-revios-desktop-wallpaper.jpg
"""

[embed]
enabled = false
