[command]
name = "weather-news"
keywords = ["widget"]
enabled = true
content = """
To remove the widgets, Windows Feeds and Interests feature from **Windows 11**,
run the following commands in an terminal as administrator:

```ps
winget uninstall --id 9MSSGKG348SP
reg delete "HKLM\\SOFTWARE\\Policies\\Microsoft\\Windows\\Windows Feeds" /v "EnableFeeds" /f
reg delete "HKCU\\Software\\Microsoft\\Windows\\CurrentVersion\\Feeds" /v "ShellFeedsTaskbarViewMode" /f
reg delete "HKCU\\Software\\Microsoft\\Windows\\CurrentVersion\\Explorer\\Advanced" /v "TaskbarDa" /f
reg delete "HKLM\\SOFTWARE\\Policies\\Microsoft\\Dsh" /v "AllowNewsAndInterests" /f
```
"""

[embed]
enabled = true
